name: cognicare
description: A dementia support Flutter application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.9

  wear_plus: ^1.2.4

  # Firebase - Updated versions
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1

  # Local notifications - Updated version
  flutter_local_notifications: ^20.0.0

  # Location
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  permission_handler: ^11.0.1


  # State management & storage
  provider: ^6.1.1
  shared_preferences: ^2.3.5

  # UI - Updated versions
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  #PHONE calling
  url_launcher: ^6.2.1

  # Timezone
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_no_text.png