name: cognicare
description: A dementia support Flutter application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10

  # Local notifications
  #flutter_local_notifications: ^15.1.0

  # Location
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0

  # State management & storage
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
